kind: pipeline
type: docker
name: default

steps:
- name: clean
  image: docker:latest
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker stop strapi || true
  - docker rm strapi || true

- name: build
  image: node:alpine
  commands:
  - cd app
  - yarn
  - yarn build

- name: start
  image: node:alpine
  commands:
  - yarn start

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock