kind: pipeline
type: docker
name: default

- name: build
  image: node:alpine-14
  commands:
  - cd app
  - yarn
  - yarn build

- name: start
  image: node:alpine-14
  commands:
  - yarn start

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock