version: '3'
services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${DB_DATABASE}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'